#!/bin/bash

launcher() {
    LOCK_FILE_LAUNCHER="$HOME/.cache/eww-launcher.lock"

run() {
    /home/icarus/eww/target/release/eww open launchermenu -c ~/.config/eww
}

# Open widgets
if [[ ! -f "$LOCK_FILE_LAUNCHER" ]]; then
    /home/icarus/eww/target/release/eww close launchermenu -c ~/.config/eww
    touch "$LOCK_FILE_LAUNCHER"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_LAUNCHER" ]]; then
    /home/icarus/eww/target/release/eww close launchermenu -c ~/.config/eww
    rm "$LOCK_FILE_LAUNCHER" && echo "closed"
fi
}

launcher