#!/bin/sh

action=$@

if [ $action == "inc" ];
then
  busctl --user call org.clight.clight /org/clight/clight org.clight.clight IncBl d 0.05
elif [ $action == "dec" ];
then
  busctl --user call org.clight.clight /org/clight/clight org.clight.clight DecBl d 0.05
fi
